#endpoints.trace.sensitive=false
#ribbon.eureka.enabled=false

server:
  port: 8000

spring:
  cloud:
    gateway:
      routes:
      - id: multiplications
        uri: http://localhost:8080/multiplications
        predicates:
          - Path=/multiplications/**
      - id: results
        uri: http://localhost:8080/results
        predicates:
          - Path=/results/**
      - id: leaders
        uri: http://localhost:8081/leaders
        predicates:
          - Path=/leaders/**
      - id: stats
        uri: http://localhost:8081/stats
        predicates:
          - Path=/stats/**

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    gateway:
      enabled: true