server:
    port: 8000

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: gateway, routes, trace

  endpoint:
    gateway:
      enabled: true
      sensitive: false
    routes:
      enabled: true
      sensitive: false
    trace:
      enabled: true
      sensitive: false

resilience4j:
  timelimiter:
    configs:
      default:
        cancelRunningFuture: false
        timeoutDuration: 5s
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true # actuator를 통해 circuitbraker 상태를 확인하기 위해 설정
        minimumNumberOfCalls: 2 # Circuit Breaker가 에러 비율 또 slow call 비율을 계산하기 전에 요구되는 최소한의 요청 수
        failureRateThreshold: 50  # 에러 비율 (퍼센트)로 해당 값 이상으로 에러 발생시 서킷이 Open 된다.
        waitDurationInOpenState: 5s  # 서킷의 상태가 Open에서 Half-open으로 변경되기 전에 Circuit Breaker가 기다리는 시간
    instances:
      myCircuitBreaker:
        baseConfig: default

spring:
  application:
    name: gateway
  cloud:
    circuitbreaker:
      resilience4j:
        enabled: true
    loadbalancer:
      ribbon:
        enabled: false
      health-check:
        enabled: true
        type: HTTP
        interval: 10s
        retries: 3
        path:
          multiplication: /actuator/health/multiplication
          gamification: /actuator/health/gamification
        service-name: multiplication, gamification
    gateway:
      # cors ?? ??
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 'http://localhost:9090' # client tomcat 서버
            allow-credentials: true
            allowedHeaders: '*'
            allowedMethods:
              - PUT
              - GET
              - POST
              - DELETE
              - OPTIONS

      # route ??
      routes:
        - id: multiplications
          uri: lb://multiplication
          predicates:
            - Path=/api/multiplications/**
          filters:
            - RewritePath=/api/multiplications, /multiplications
            - name: CircuitBreaker
              args:
                name: myCircuitBreaker
                fallbackUri: forward:/fallback

        - id: results
          uri: lb://multiplication
          predicates:
            - Path=/api/results/**
          filters:
            - RewritePath=/api/results, /results

        - id: leaders
          uri: lb://gamification
          predicates:
            - Path=/api/leaders/**
          filters:
            - RewritePath=/api/leaders, /leaders

        - id: stats
          uri: lb://gamification
          predicates:
            - Path=/api/stats/**
          filters:
            - RewritePath=/api/stats, /stats